import { Injectable } from '@angular/core';
import { Legend } from '../legend';


@Injectable({
  providedIn: 'root'
})
export class LegendsService {


constructor() { }

  getLegends(): Legend[] {
    return [
      {id:1, name: 'BloodHound', type:'Eclaireur', image:'Blood.png', description:'Bloodhound passe dans les Terres Sauvages pour l\'une des plus grandes chasseuses que la Frontière ait connue - et c\'est à peu près tout ce que l\'on sait d\'elle. Enfant de deux ingénieurs détachés sur le site nucléaire de New Dawn sur la planète Talos, Bloodhound a été élevée par son oncle Artur après la mort de ses deux parents suite à la destruction de la centrale provoquée par la fusion du cœur de réacteur. Artur a enseigné à Bloodhound les traditions ancestrales qui glorifient la nature et rejettent la technologie moderne. Il n’en reste pas moins que Bloodhound a grandi en étant secrètement attirée par les innovations technologiques. Lors d’une épreuve de chasse constituant son rite de passage à l’âge adulte, elle a décidé de recourir à des méthodes à la fois anciennes et avant-gardistes pour éliminer un Goliath qui terrorisait son village. Cet événement fondateur a changé le cours de sa vie.', realName:'Inconnu', years:0, originWorld:'Talos',tactique:'Œil du Faiseur d\'Orages', passive:'Traqueur', ultime:'Prédateur', bg:'bg-bloodhound.jpg'},

      {id:2, name: 'Gibraltar', type:'Tank', image:'Gigi.png', description:'Gibraltar est un gentil géant doté d\'un tempérament parfois sauvage. Fils de deux bénévoles de l\'association SARAS (Search and Rescue Association of Solace), il a toujours été doué pour sauver les autres des situations périlleuses malheureusement récurrentes dans les Terres Sauvages. Il a pris pleinement conscience de la valeur de ces opérations de sauvetage lorsque lui et son copain ont volé la moto de son père pour partir en virée et se sont retrouvés piégés au milieu d\'une coulée de boue. Ses parents les ont secourus mais son père y a laissé un bras. Gibraltar n\'a jamais oublié ce sacrifice et a consacré sa vie à venir en aide aux plus démunis.', realName:'Makoa Gibraltar', years:30, originWorld:'Solace',tactique:'Dôme protecteur', passive:'Blindage d\'armement', ultime:'Pilonnage défensif',bg:'bg-gibraltar.jpg' },

      {id:3, name: 'Lifeline', type:'Soutien', image:'Lifeline.png', description:'On peut se demander pourquoi Ajay Che, alias Lifeline, participe aux Jeux Apex. Enfant de parents dont les affaires ont prospéré grâce à la guerre, elle a quitté son foyer le jour où elle a compris les malheurs qu\'engendrait la richesse de sa famille et elle s\'est engagée dans l\'organisation humanitaire Frontier Corps, qui vient en aide aux communautés de la Frontière dans le besoin. Elle a depuis consacré sa vie à venir en aide aux plus démunis et participe aux Jeux Apex dans l\'espoir de financer Frontier Corps grâce à ses gains.', realName:'Ajay Che', years:24, originWorld:'Psamathe',tactique:'Drone-médecin DOC', passive:'Secouriste de combat', ultime:'Pack de soutien',bg:'bg-lifeline.jpg' },

      {id:4, name: 'Pathfinder', type:'Eclaireur', image:'Pathfinder.png', description:'Malgré son parcours, Pathfinder est un véritable symbole d\'optimisme. Unité opérationnelle MRVN (Mobile Robotic Versatile eNtity, alias "Marvin") spécialisée dans la reconnaissance et la surveillance, Pathfinder a été mis en service il y a plusieurs décennies dans un entrepôt désaffecté, sans savoir qui l’avait créé ni pourquoi.  Avec son matricule MRVN pour seule identité, l’androïde s’est mis en tête de retrouver son créateur.', realName:'MRVN', years:0, originWorld:'Il cherche à le découvrir !',tactique:'Grappin', passive:'	Délit d\'initié', ultime:'Lance-tyrolienne',bg:'bg-pathfinder.jpg' },

      {id:5, name: 'Wraith', type:'Assaut', image:'Wraith.png', description:'Wraith est une véritable tornade capable d\'exécuter des attaques aussi rapides que fatales, mais aussi de manipuler l\'espace-temps en ouvrant des failles dans notre réalité. Ces dons ne l\'ont pas laissée indemne. Il y a plusieurs années, elle s\'est réveillée dans un centre de détention de l\'IMC sans aucun souvenir de sa vie antérieure... Renee Blasey, scientifique en chef, avait accepté de servir de cobaye pour ses propres expérimentations. Son associé l\'avait alors trahie et fait enfermer : Renee n\'existait plus. Elle était devenue une jeune femme craintive, harcelée par une cacophonie de voix qu\'elle seule entendait, jusqu\'à ce qu\'une autre version d\'elle-même apparaisse et lui apprenne à les écouter. Grâce à son double, Wraith a trouvé la force nécessaire pour s\'échapper de prison et passer dans une autre réalité. Notre réalité.', realName:'	Renee Blasey', years:32, originWorld:'Typhon',tactique:'Dans le vide', passive:'Voix du Vide', ultime:'Faille dimensionnelle',bg:'bg-wraith.jpg' },

      {id:6, name: 'Bangalore', type:'Assaut', image:'Bangalore.png', description:'Née dans une famille militaire dont ses parents, ses quatre grands frères et elle-même ont tous servi au sein des forces de l\'IMC, Bangalore a toujours été un soldat exceptionnel. Sortie major de l\'Académie militaire de l\'IMC, elle reste l\'unique élève officier capable en moins de 20 secondes de démonter puis de remonter un Peacekeeper après l\'avoir équipé d\'un choke de précision... les yeux bandés.', realName:'Anita Williams', years:38, originWorld:'Gridiron',tactique:'Lance-fumigène', passive:'Pas de charge', ultime:'Pas de charge',bg:'bg-bangalore.jpg' },

      {id:7, name: 'Caustic', type:'Tank' , image:'Caustic.png', description:'Avant de se faire connaître sous l\'inquiétant surnom de Caustic, le chercheur Alexander Nox était l’un des plus brillants employés des laboratoires Humbert, l\'un des principaux fournisseurs de pesticides à la Frontière. Comme il fallait toujours plus de pesticides pour protéger les cultures dans les colonies frontalières, Nox travaillait d\'arrache-pied pour mettre au point de nouvelles formules. Ses progrès étaient toutefois entravés par les protocoles de test qu’il devait suivre. Pour s\'assurer de l’efficacité de ses substances gazeuses, il ne pouvait se contenter de les tester sur des surfaces inertes : il avait besoin d\'êtres vivants comme cobayes..', realName:'Alexander Nox', years:48, originWorld:'Gaea',tactique:'Piège à gaz Nox', passive:'Vision Nox', ultime:'Grenade à gaz Nox',bg:'bg-caustic.jpg'},

      {id:8, name: 'Mirage', type:'Assaut', image:'Mirage.png', description:'Mirage aime qu\'on le remarque. Benjamin d\'une fratrie de quatre garçons, il a fait de ses pitreries sa marque de fabrique pour attirer l\'attention. La seule chose qu\'il a prise au sérieux, c\'est la technologie de l\'holo-pilote : initié à l\'art de l\'illusion par sa mère ingénieur, il s\'est amouraché de cette technologie et a tout appris de ses mécanismes. Même lorsque ses frères ont été portés disparus au cours de la Guerre frontalière, Mirage et sa mère ont continué à développer des dispositifs holographiques, et leur travail les a rapprochés.', realName:'Elliott Witt', years:30, originWorld:'Solace',tactique:'Dissuasion', passive:'Insaisissable', ultime:'Extravagance',bg:'bg-mirage.jpg'},

      {id:9, name: 'Octane', type:'Assaut', image:'Octane.png', description:'Un jour, Octavio Silva s\'ennuyait. Comme presque tous les jours, en fait. Fils du PDG débordé de Silva Pharmaceuticals et n\'attendant rien de la vie, il avait pris l\'habitude de défier la mort en réalisant toutes sortes de cascades avant d\'en publier des holovidéos pour impressionner ses nombreux fans. Ce jour-là, il s’était mis en tête de battre le record du parcours d’entraînement local en se propulsant vers la ligne d\'arrivée au moyen d\'une grenade.', realName:'Octavio Silva', years:24, originWorld:'Psamathe',tactique:'Stimulant', passive:'Guérison rapide', ultime:'Tremplin',bg:'bg-octane.jpg' },

      {id:10, name: 'Wattson', type:'Tank', image:'Wattson.png', description:'Natalie "Wattson" Paquette est une figure bien connue des Jeux Apex, même si c\'est pour une raison très précise. Fille de l\'ingénieur en charge de l\'installation électrique des Jeux, elle a étudié ses manuels pour rester auprès de lui. C\'est ainsi qu\'elle a découvert très jeune sa vocation. S\'il lui arrivait d\'être totalement concentrée puis distraite la seconde suivante, elle a trouvé l\'inspiration dans l\'électricité, dont le flux régulier a vite donné un sens à sa vie qu\'elle ne trouvait nulle part ailleurs.', realName:'Natalie Paquette', years:22, originWorld:'Solace',tactique:'Périmètre de sécurité', passive:'Éclair de génie', ultime:'Pylône d’interception',bg:'bg-wattson.jpg' },

      {id:11, name: 'Crypto', type:'Eclaireur', image:'Crypto.png', description:'Crypto est le spécialiste des secrets. Hacker de génie et expert en cryptage, il met à profit ses drones aériens pour épier ses adversaires dans l\'arène d\'Apex sans se faire repérer. Mais lui aussi cache un lourd secret. Son vrai nom est Tae Joon Park, et il participe aux Jeux Apex pour identifier ceux qui l’ont accusé à tort de meurtre.', realName:'Tae Joon Park', years:31, originWorld:'Gaea',tactique:'Drone de surveillance', passive:'Neurolien', ultime:'Drone IEM',bg:'bg-crypto.jpg'},

      {id:12, name: 'Revenant', type:'Assaut', image:'Revenant.png', description:'Autrefois, Revenant était encore humain. C’était même le plus dangereux tueur à gages que le Syndicat Mercenaire ait jamais connu. Quand il se regardait dans le miroir, c\'était un visage d\'homme qu\'il voyait. Mais le temps a fait son œuvre et, quand son programme s\'est mis à défaillir, il a vu ce que le Syndicat Mercenaire et Hammond Robotics avaient fait de lui : un cauchemar ambulant fait d’acier et de chair résiduelle. Ses maîtres le ressuscitaient en tant que simulacre, l\'arrachant à l\'étreinte de la mort, encore et encore, en le programmant pour oublier.', realName:'Inconnu', years:0, originWorld:'Solace',tactique:'Silence', passive:'Traqueur', ultime:'	Totem de frag',bg:'bg-revenant.jpg'},

      {id:13, name: 'Loba', type:'Soutien', image:'Loba.png', description:'À l\'âge de neuf ans, Loba a assisté au meurtre de sa famille par le simulacre Revenant, un tueur à gages sans merci. Livrée à elle-même, Loba a survécu en devenant pickpocket. En peaufinant méthodiquement ses compétences, Loba a employé tous les moyens à sa disposition pour s\'élever dans la société. Tout a changé le jour où Loba est parvenue à s’introduire dans un complexe réputé impénétrable, s\'emparant ainsi d\'un disque de saut unique en son genre. Dotée d\'un bracelet de téléportation, Loba pouvait désormais mettre la main sur les objets les plus rares et les mieux gardés. Elle allait enfin pouvoir mener la grande vie et rejoindre l’élite.', realName:'Loba Andrade', years:34, originWorld:'Inconnu',tactique:'Monte-en-l\'air', passive:'Regard aiguisé', ultime:'Boutique du Marché Noir',bg:'bg-loba.jpg' },

      {id:14, name: 'Rampart', type:'Tank', image:'Rampart.png', description:'Propriétaire d\'un atelier indépendant, Rampart n\'a besoin que d\'un gros calibre et d\'un sac à dos rempli de ferraille pour survivre dans les impitoyables Terres Sauvages. Avant de monter son affaire florissante sur Gaea, Ramya Parekh (Rampart pour les intimes) a forgé sa réputation en prenant part à des épreuves clandestines. Parekh s\'est hissée au sommet en faisant preuve d\'un talent hors normes avec son équipement modifié. Elle a ensuite commencé à nouer des contrats avec des contrebandiers, des membres du Syndicat et d\'autres individus peu fréquentables. Pour certains, la seule valeur sûre porte la marque de Rampart.', realName:'Ramya Parekh', years:21, originWorld:'Gaea',tactique:'Champ de force', passive:'Chargeur modifié', ultime:'Mitrailleuse montée Sheila',bg:'bg-rampart.jpg' },

      {id:15, name: 'Horizon', type:'Assaut', image:'Horizon.png', description:'Il y a près d’un siècle, les Terres Sauvages étaient au bord d’une crise énergétique aux proportions cataclysmiques. Le Dr Mary Somers, une astrophysicienne aussi charmante qu’excentrique, fut sommée de trouver une solution. Mary déménagea à Olympus avec sa famille pour mener des recherches dans une station scientifique de haute technologie. Avec l\'aide du Dr Reid, son énigmatique apprentie, Mary découvrit que le branthium était la clé d’une source d’énergie potentiellement illimitée. Cette matière rare étant uniquement accessible sur le disque d’accrétion des trous noirs, Mary et le Dr Reid se lancèrent dans une mission à haut risque pour vérifier cette théorie.', realName:'Dr Mary Somers', years:37, originWorld:'Psamathe',tactique:'Ascenseur de gravité', passive:'Spationaute', ultime:'Trou noir',bg:'bg-horizon.jpg' },

    ]
  }

  // 5 on crée une fonction qui récupére une seul légende en se servant de son name
  getOneLegend(name):Legend {
    console.log(name);

    // 6  On va dans le tableau de toutes les légendes 
    //    on cherche dans ce tableau un élément ) Legend
    //    Dans l'élément Legend on cherche son nom 
    //    son nom = name qui servira pour l'url 
    return this.getLegends().find( Legend => Legend.name === name);
    
  }

}
